-- What the game says when it asks whether you are ready.
--
-- Generated by tools/build-readycheck-index.ps1 - do not edit by hand.
-- Source: Shared.pak and Gustav.pak of 2026-07-29, Localization/ReadyChecks_Descriptions
-- plus the ready-check rows of the Misc tables beside them.
--
-- A ready check is the only warning the game gives before something that cannot be undone.
-- The story names the message; the layer says it. No text here, only handles - the game
-- turns them into sentences in its own language through Ext.Loca.
--
--   M.msg[messageKey] = handle

local M = {}
M.BUILD = "rcdata 2026-07-29"

M.msg = {
["CRE_AstralPrison_Entering_ReadyCheck"]="hbb4deb16g2b93g4c43gb5e3g7d1832e021db",
["CRE_AstralPrison_Leaving_ReadyCheck"]="hce6aef67gb01ag4780gac1fgcf2d499b3ff6",
["END_ReadyMessage_BrainStem"]="had1ef09cg758bg4b17g86f9g86409207f3fa",
["END_ReadyMessage_LeaveAstralPrism"]="h73bb9674gb05eg4078gb022gb389439a5a45",
["END_ReadyMessage_MorphicPool"]="h8fcb31ecg485dg4139gb9b7g36ae1f5b9c06",
["EPI_ReadyMessage_FinalToast"]="hc4b4f81bge2b6g437fg8df4g7c27bce97a85",
["GLO_Waypoint_Regionswap"]="hd9f30aeag8bdfg4ab0g8975g617605a6f426",
["INT_EmperorRevealed_Leaving_ReadyCheck"]="h8962b296g50a9g4536gb5e6gdc8122f66c16",
["LOW_DevilsFee_PortalToDevilsFee_Message"]="h4c1e27c5gfe9eg4e2eg92e4g9ef150ae7b9b",
["LOW_DevilsFee_PortalToHouseOfHope_Message"]="h5511f017g3e23g467bg8d08gbc0e91ea2b8a",
["LOW_DevilsFee_Underleveled_ReadyCheck"]="h51c15378g2587g41degbcf5gf6711aa26d59",
["LOW_DockWarehouse_ToIronThrone_ReadyCheck"]="h3a3a84c8gcc3cg41deg8fd8g67b933f54178",
["LOW_HouseOfHope_GatherParty"]="h512757aeg2ce3g42a7gb0ceg8da446977a52",
["LOW_IronThrone_ToDockWarehouse_ReadyCheck"]="hee28b274gf78fg43c8g9227g3c9831ede461",
["LOW_IronTrone_ToBasement_ReadyCheck"]="h1d4ce893g20f3g4db6ga998gf93d2efb2bb4",
["Message_ProgressingWorldState"]="h6cfe88d4g6dedg40edga8bbg19e3e77e49cc",
["MOO_Assault_ReadyCheck"]="hcd89dd30gc11cg40efg8d32ge4a7400fc863",
["MOO_Audience_ReadyCheck"]="h31b4028bg71d9g49dfg8809gf2aec12c3aeb",
["ReadyCheck_EbonLake"]="hd9978b23gdbd1g48ebg86f0g6868f526d109",
["ReadyCheck_EndEarlyAccess"]="h3900af2bg7e9cg4c78gbd89g7935184ff0a4",
["ReadyCheck_EndEarlyAccessElevator"]="h22d87d51g6bbfg4a83ga175gc72e98dd8abb",
["ReadyCheck_EndNight"]="h233f2f10gb31bg4480g8b79gf6163a4ce5a1",
["ReadyCheck_EndNight_RequiredTalksLeft"]="heb3d52f1ge7bbg48b4ga1abg6792e905e1bc",
["ReadyCheck_EndNight_TalksLeft"]="hcb21cfabg78a2g446agbf23g5bd820720a07",
["ReadyCheck_GoToNight"]="h2908c522gaea2g457ag9d0fg05ab7a55961b",
["ReadyCheck_GoToNight_DangerZone"]="he0d0d5f0g227cg4e36gb73dg998083bab4a0",
["ReadyCheck_GoToNight_LocalRest"]="h01a9fca9gf1b7g4e58g8c0agf1961eda77e4",
["ReadyCheck_GoToNight_NoCamp"]="hdc1c2f1bg7db2g45d8g988bgd17821517dc0",
["ReadyCheck_PartyMemberNotReady"]="h056e3dacg3ed5g4d7egb791g96c8af3f4e51",
["ReadyCheck_RegionSwap"]="hf73db232g958eg4f6fgb171gf2ffb945236a",
["ReadyCheck_RegionSwap_CanReturn"]="h7cba185eg98aag4c52g8e37g8c6fcb5dd009",
["ReadyCheck_RegionSwap_CanReturn_LowLevel"]="hd7d4d9e9g8e9eg4cb5g8851g80b6c4f4361a",
["ReadyCheck_RegionSwap_LowLevel"]="h9ab5c858g742bg44fbgbe68g54c7c61ea2e3",
["ReadyCheck_YouAreNotReady"]="h2e7a2776g3849g4bf2g9afegb6291f581c61",
["TUT_Helm_EnterHelmCheck"]="h362a8562ga484g4e03g9e36g260f9979ff9a",
["TWN_Finale_CompanionReadyCheck"]="hce0614c6g8576g4379g8263g326164bc8be2",
["TWN_Finale_DepartureCheck"]="h8c58a11fgd206g4deeg85b3g44a716b63b4c",
}

return M
